### ISSUE TITLE
Error message during CMK update from 2.1.0p14.cre to 2.1.0p15.cre

### ISSUE THREAD

**Issue by sourceforge807** [edvler/check_mk_proxmox-qemu-backup#24]
Hello,

during the update from p14 to p15 it shows me the following error:

Failed to load plugin /omd/sites/monitoring/local/share/check_mk/web/plugins/wato/check_parameters_proxmox_qemu_backup.py: module 'cmk.utils.version' has no attribute 'is_enterprise_version'
-| Traceback (most recent call last):
-|   File "/omd/sites/monitoring/lib/python3/cmk/gui/utils/__init__.py", line 186, in load_web_plugins
-|     exec(f.read(), globalvars)
-|   File "<string>", line 70, in <module>
-| AttributeError: module 'cmk.utils.version' has no attribute 'is_enterprise_version'
-| 
-| ERROR: Failed to load some GUI plugins. You will either have 
-|        to remove or update them to be compatible with this 
-|        Checkmk version.
-| 
-| Updating Checkmk configuration...
-| ATTENTION: Some steps may take a long time depending on your installation, e.g. during major upgrades.
-|  1/27 Rewriting password store...
-|  2/27 Migrate Visuals context...
-|  3/27 Update global settings...
-|  4/27 Rewriting tags...
-|  5/27 Rewriting hosts and folders...
-|  6/27 Rewriting rulesets...
-| Replacing ruleset non_inline_snmp_hosts with snmp_backend_hosts
-|  7/27 Rewriting discovered host labels...
-|  8/27 Rewriting autochecks...
-|  9/27 Cleanup version specific caches...
-|  10/27 Migrating fs_used name...
-|  11/27 Migrate pagetype topics...
-|  12/27 Migrate dashlets...
-|  13/27 Migrate LDAP connections...
-|  14/27 Rewrite BI Configuration...
-| Skipping conversion of bi.mk (already done)
-|  15/27 Set version specific user attributes...
-|  16/27 Rewriting inventory data...
-| Skipping py2 inventory data update (already done)
-|  17/27 Migrate audit log...
-| No audit log present. Skipping.
-|  18/27 Sanitize audit log (Werk #13330)...
-| Skipping (already done)
-|  19/27 Rename discovered host label files...
-|  20/27 Rewriting host, service or contact groups...
-|  21/27 Rewriting notification configuration for ServiceNow...
-|  22/27 Renewing certificates without server name extension...
-| Skipping (nothing to do)
-|  23/27 Adding site CA to trusted CAs...
-|  24/27 Rewrite mknotifyd config for central site...
-|  25/27 Rewriting InfluxDB connections...
-|  26/27 Disabling unsafe EC rules...
-|  27/27 Update bakery links and settings...
-| Done

To fix the error:
remove    if cmk_version.is_enterprise_version() or cmk_version.is_managed_version():
add         if cmk_version.is_enterprise_edition() or cmk_version.is_managed_edition():

in check_parameters_proxmox_qemu_backup.py

**Comment by edvler** [comment]
Released complete new Version for Checkmk 2.4.  It's under review in the Checkmk Exchange. In the meanwile use the mkp from the dist-folder.
